version: "3.9"
   
services:
  db:
    image: postgres:14.3
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
  redisdb:
    image: redis:6.2-alpine
    volumes:
      - ./db/redis/data:/data
    env_file: .env
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 600 1 --loglevel warning
  webapp:
    build: .
    command: apache
    volumes:
      - .:/npdb
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
      - redisdb
    env_file: .env
