version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5432:5432
  webapp:
    build: .
    command: apache
    volumes:
      - .:/npdb
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    env_file: .env
